--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Nnse/libCustomItem
build-by-default: true
branches:
- master
projects:
  libCustomItem:
    path: ""
    model: virion
    type: library
...
